name: Cypress run test
on: 
  push:
      branches: [ main ]
  schedule:
     - cron:  '30 5 * * *'
jobs:
 cypress-run-mac:
    runs-on: windows-latest
    strategy:
      matrix:
        node: [10, 12, 14, 16]
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
            node:version: '14'
      - name: Install dependencies
        run: npm install     
      - name: Cypress run
        timeout-minutes: 45
        uses: cypress-io/github-action@v2
        with:
          start: npm test
  
    


